server:
  port: 9000

application:
  qiniu:
    accessKey: zuBdrSZjaBz7rw0GlpAgiKvR9gA86obUiWX9cPqo
    secretKey: uxtunuTJB2oHwUJNYVR-cfaYOHwMjyFauDCkfEZL
    bucket: soulmate1214
    area: hua_nan
    domain: image.ayue.wiki
    dirName: graduation-picture
  wechat:
    appId: wx3df74b3800d2d392
    secret: fe8b2848edec65872ad393b13de40db4

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://118.24.1.170:5432/graduation-picture
    username: picture
    password: 123456789
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
