server:
  port: 9000

application:
  qiniu:
    accessKey: zuBdrSZjaBz7rw0GlpAgiKvR9gA86obUiWX9cPqo
    secretKey: uxtunuTJB2oHwUJNYVR-cfaYOHwMjyFauDCkfEZL
    bucket: soulmate1214
    area: hua_nan
    domain: image.ayue.wiki
    dirName: graduation-picture

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://118.24.1.170:5432/graduation-picture
    username: picture
    password: 123456789